# Generated by Django 5.0.3 on 2024-03-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=40)),
                ('why', models.TextField()),
                ('moving_date', models.DateTimeField()),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.student')),
            ],
        ),
    ]
