# Generated by Django 5.0.3 on 2024-03-26 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_card_why_alter_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=40)),
                ('why', models.TextField(blank=True, null=True)),
                ('moving_date', models.DateTimeField()),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.student')),
            ],
        ),
    ]
