# Generated by Django 5.0.3 on 2024-03-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_precard'),
    ]

    operations = [
        migrations.AddField(
            model_name='precard',
            name='time',
            field=models.CharField(choices=[('1차야자', '1차야자'), ('8, 9교시', '8, 9교시')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
