# Generated by Django 5.0.3 on 2024-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_precard_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ip',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='precard',
            name='ip',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
