# Generated by Django 5.0.3 on 2024-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_alter_precard_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precard',
            name='stu',
        ),
        migrations.AddField(
            model_name='precard',
            name='pw',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='precard',
            name='stus',
            field=models.ManyToManyField(to='pybo.student'),
        ),
    ]
